n1 = int(input("Welk getal wilt u voor nummer 1? : "))
n2 = int(input("Welk getal wilt u voor nummer 2? : "))
n3 = int(input("Welk getal wilt u voor nummer 3? : "))
n4 = int(input("Welk getal wilt u voor nummer 4? : "))
n5 = int(input("Welk getal wilt u voor nummer 5? : "))
n6 = int(input("Welk getal wilt u voor nummer 6? : "))
n7 = int(input("Welk getal wilt u voor nummer 7? : "))
n8 = int(input("Welk getal wilt u voor nummer 8? : "))
n9 = int(input("Welk getal wilt u voor nummer 9? : "))
n10 = int(input("Welk getal wilt u voor nummer 10? : "))

print (int(n1 + n2))
print (int(n3 - n4))
print (int(n5 * n6))
print (int(n7 / n8))
print (int(n9 + 1))
print (int(n10 - 1))